clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/125kx_inchalla/A.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AACG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AACI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AACIU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AACIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AADI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAIC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAMC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAME.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAOI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAON.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAPL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAQC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AATC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AAWW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABBV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABCB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABCL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABCM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABEO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABEV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABGI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABIO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABMD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABNB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABOS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABSI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABST.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABTX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABUS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ABVC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACABU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAHU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAHW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAQ.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAXR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAXU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACAXW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACEL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACER.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACET.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACEV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACEVU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACGL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACGLN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACGLO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACHC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACHL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACHR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACHV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACII.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACIU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACMR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACNB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACON.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACONW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACOR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACQR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACQRU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACRO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACRS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACRX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACST.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACTD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACVA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ACXP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADAG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADAL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADAP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADBE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADCT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADER.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADERW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADES.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADEX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADGI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADIL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADMA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADMP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADNT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADOC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADOCR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADOCW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADPT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADRA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADRT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADSE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADSEW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADSK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADTH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADTHW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADTN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADTX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADUS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADVM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ADXN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEAC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEFC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEIS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEMD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AENZ.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEPPZ.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AER.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AERC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AERI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AES.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AESC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AESC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEVA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AESE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEYE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AEZS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFAC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFACW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFAQ.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFAQU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFAQW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFBI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFCG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFGB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFGC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFGD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFGE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFIB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFMD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFRM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFTR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AFYA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGAC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGBA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGBAR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGBAW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGCB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGCO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGEN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGFS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGFY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGGR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGGRU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGIL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGILW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGIO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGLE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGMH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGNC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGNCM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGNCN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGNCO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGNCP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGRI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGRIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGRO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGRX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGTC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGTI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AGYS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHCO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHPA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHPAU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHPAW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHPI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHRN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHRNU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AHT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIHS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIKI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIMAU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIMC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AINC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AINV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIRC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIRG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIRI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIRS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIRT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIRTP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIZ.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AIZN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AJG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AJRD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AJX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AJXA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKAM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKAN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKBA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKIC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKRO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKTS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKTX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKUS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AKYA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALBO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALCC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALCO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALDX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALEC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALEX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALFIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALGM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALGN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALGS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALGT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALHC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALIT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALJJ.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALKS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALLY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALNA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALNY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALOR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALORU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALORW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALOT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALPA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALPAW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALPN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALPP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALRM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALRN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALRS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALSA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALSAR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALSAW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALSN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALTG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALTO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALTR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALTU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALTUU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALTUW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALVR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALXO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALYA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ALZN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMAL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMAM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMAO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMAOW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMAT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMBA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMBC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMBO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMBP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMCI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMCIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMCR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMCX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AME.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMED.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMEH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMGN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMKR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMLX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMNB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMOT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMOV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPGW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMPY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMRC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMRK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMRN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMRS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMRX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMSC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMSF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMST.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMSWA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMTB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMTD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMTI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMTX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMWD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMWL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMYT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AMZN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANAB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANAC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANAT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANDE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANEB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANET.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANGH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANDE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANEB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANET.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANGH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANGHW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANGI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANGN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANGO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANIK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANIP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANIX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANPC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANSS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANTE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANTM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANTX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANVS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANZU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANZUU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ANZUW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOGO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOGOW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOMR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AON.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AORT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOSL.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AOUT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APAC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APACW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APAM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APCA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APCX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APCXW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APDN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APEI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APEN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APGB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/API.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APLD.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APLE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APLS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APLT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APM.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APMI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APMIU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APMIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APOG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APP.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APPF.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APPH.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APPHW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APPN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APPS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APRE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APRN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APSG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APT.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APTMU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APTMW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APTO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APTS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APTV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APTX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APVO.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APWC.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APXI.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APXIU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APXIW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/APYX.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQMS.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQN.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQNA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQNB.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQNU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQST.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AQUA.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/AR.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARAV.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARAY.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARBE.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARBEW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARBG.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARBGU.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARBGW.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARBK.py &
python3 /home/ubuntu/Desktop/125kx_inchalla/ARC.py 


